[tool.poetry]
name = "tests"
version = "0.1.0"
description = ""
authors = ["chachaleo <charlotte.leo@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.21.0"
onnx = "^1.10.1"
onnxruntime = "^1.10.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.1"
pre-commit = "^3.6.0"
ruff = "^0.1.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

