[package]
name = "primops-decomp"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.1"
onnx = { path = "../onnx" }
orion = { path = "../orion" }
onnx-decomp = { path = "../onnx-decomp" }